### ISSUE TITLE
Recently upgraded Manifold instance cannot start Elastic Search service

### ISSUE THREAD

**Issue by hardyoyo** [ManifoldScholar/manifold-omnibus#43]
We recently upgraded our instance of Manifold from 4.1.0~beta.1-1.el7 to 5.0.0-1.el7 (and ran into some difficulty, which we logged on issue #42). A user noticed that searching wasn't working. In troubleshooting, we determined that the Elastic Search service was not booting up correctly. Looking at the log files:

```
2020-07-16_22:11:08.31908 [2020-07-16T22:11:08,314][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
2020-07-16_22:11:08.31923 org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: plugins directory [/opt/manifold/embedded/elasticsearch/plugins] not found
2020-07-16_22:11:08.31928 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.15.jar:5.6.15]
2020-07-16_22:11:08.31932 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.15.jar:5.6.15]
2020-07-16_22:11:08.31938 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.15.jar:5.6.15]
2020-07-16_22:11:08.31944 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.15.jar:5.6.15]
2020-07-16_22:11:08.31952 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.15.jar:5.6.15]
2020-07-16_22:11:08.31958 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.15.jar:5.6.15]
2020-07-16_22:11:08.31963 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.15.jar:5.6.15]
2020-07-16_22:11:08.31968 Caused by: java.lang.IllegalStateException: plugins directory [/opt/manifold/embedded/elasticsearch/plugins] not found
2020-07-16_22:11:08.31974 	at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:69) ~[elasticsearch-5.6.15.jar:5.6.15]
2020-07-16_22:11:08.31979 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:168) ~[elasticsearch-5.6.15.jar:5.6.15]
2020-07-16_22:11:08.31983 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.15.jar:5.6.15]
2020-07-16_22:11:08.31987 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.15.jar:5.6.15]
2020-07-16_22:11:08.31992 	... 6 more
```
I could see that ES was failing to load because it could not find this plugins folder:
`/opt/manifold/embedded/elasticsearch/plugins`

I confirmed this folder did not exist, created it manually, and restarted ES with a `sudo manifold-ctl restart elasticsearch` command. I confirmed the service was indeed up:

```
sudo netstat -plunt | grep 3036
tcp6       0      0 127.0.0.1:3036          :::*                    LISTEN      26096/java
tcp6       0      0 ::1:3036                :::*                    LISTEN      26096/java
```
I then ran a reindex command successfully:
```
sudo manifold-api manifold:search:reindex
Reindexing Subject...
Reindexing Event...
Reindexing Maker...
Reindexing Annotation...
Reindexing Project...
Reindexing User...
Reindexing ResourceCollection...
Reindexing Resource...
Reindexing Tag...
Reindexing TextSection...
Reindexing Text...
Reindex complete
```

**Comment by zdavis** [comment]
Believe this will be fixed in v6.
